name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs-site/**'
      - 'scripts/build-browser/**'
      - 'src/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Cache dependencies - main project
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-main-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-main-
            
      - name: Install main project dependencies
        run: npm ci
            
      - name: Build jsq browser bundle
        run: npm run build:browser
          
      - name: Cache dependencies - docs-site
        uses: actions/cache@v4
        with:
          path: docs-site/node_modules
          key: ${{ runner.os }}-docs-site-${{ hashFiles('docs-site/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-docs-site-
            
      - name: Build documentation
        working-directory: docs-site
        run: |
          npm ci
          npm run build
          
      - name: Add .nojekyll file
        run: |
          touch docs-site/dist/jsq-docs/browser/.nojekyll
          echo "GitHub Pages will not process this site with Jekyll" > docs-site/dist/jsq-docs/browser/.nojekyll
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-site/dist/jsq-docs/browser
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4